### ISSUE TITLE
Would like a review on a portfolio Project

### ISSUE THREAD

**Issue by ribeiroAllison** [ribeiroAllison/mixed-messages#1]
Hello,

This is my first Portfolio project (also my first pull request).

It would be very helpful to get feedback from a more senior dev.

https://github.com/ribeiroAllison/mixed-messages

Cheers,
Allison

**Comment by QuinceyJames** [comment]
Hey there! 

I'm not a senior dev but I have some experience with HTML and JS. In order to make it easier for a review, I would recommend making a pull request. To do so you will have to have two branches. Ideally, your 'main' branch will be blank and your 'dev' branch will have code you want reviewed. Your pull request then asks to 'pull' your changes from dev into main. 

Feel free to ask if you have any questions!

**Comment by ribeiroAllison** [comment]
Hey  @QuinceyJames , 

Thanks so much for the feedback. I've done what you suggested. On main branch, I've deleted HTML, CSS, and JS files.

However, I could not set you as an assignee for the new pull request of dev branch. 

Here is the link to it: https://github.com/ribeiroAllison/mixed-messages/pull/2#issue-1474279666

I don't know if pull requests work like this so sorry if I'm making mistakes take makes no sense  :)

Again, thanks for taking the time to help me out.

Cheers,
Allison
